[package]
name = "torrent"
version = "0.1.0"
authors = ["Peter Kelly <peter@pmkelly.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
tokio = { version = "1.0.1", features = ["full"] }
futures = "0.3.8"
rand = "0.8.0"
openssl-sys = "0.9.60"
openssl = "0.10.32"
quiche = "0.6.0"
ring = { version = "0.16", features = ["alloc", "dev_urandom_fallback", "std"] }
rustls = { version = "0.19.1", features = ["logging", "dangerous_configuration"] }
